/**/callback({"meta": {
  "Cache-Control": "public, max-age=60, s-maxage=60",
  "Vary": "Accept",
  "ETag": "\"7ccf80a91486627cf9e5fb090e83595fa923b541718ef95d3e62293669f32e63\"",
  "Last-Modified": "Thu, 07 Oct 2021 10:05:31 GMT",
  "Content-Type": "application/javascript; charset=utf-8",
  "X-GitHub-Media-Type": "github.v3; format=json",
  "status": 200,
  "X-RateLimit-Limit": "60",
  "X-RateLimit-Remaining": "56",
  "X-RateLimit-Reset": "1633634179",
  "X-RateLimit-Used": "4",
  "X-RateLimit-Resource": "core"
}, "data": {
  "id": 59114705,
  "node_id": "MDEwOlJlcG9zaXRvcnk1OTExNDcwNQ==",
  "name": "cleave.js",
  "full_name": "nosir/cleave.js",
  "private": false,
  "owner": {
    "login": "nosir",
    "id": 352617,
    "node_id": "MDQ6VXNlcjM1MjYxNw==",
    "avatar_url": "https://avatars.githubusercontent.com/u/352617?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/nosir",
    "html_url": "https://github.com/nosir",
    "followers_url": "https://api.github.com/users/nosir/followers",
    "following_url": "https://api.github.com/users/nosir/following{/other_user}",
    "gists_url": "https://api.github.com/users/nosir/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/nosir/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/nosir/subscriptions",
    "organizations_url": "https://api.github.com/users/nosir/orgs",
    "repos_url": "https://api.github.com/users/nosir/repos",
    "events_url": "https://api.github.com/users/nosir/events{/privacy}",
    "received_events_url": "https://api.github.com/users/nosir/received_events",
    "type": "User",
    "site_admin": false
  },
  "html_url": "https://github.com/nosir/cleave.js",
  "description": "Format input text content when you are typing...",
  "fork": false,
  "url": "https://api.github.com/repos/nosir/cleave.js",
  "forks_url": "https://api.github.com/repos/nosir/cleave.js/forks",
  "keys_url": "https://api.github.com/repos/nosir/cleave.js/keys{/key_id}",
  "collaborators_url": "https://api.github.com/repos/nosir/cleave.js/collaborators{/collaborator}",
  "teams_url": "https://api.github.com/repos/nosir/cleave.js/teams",
  "hooks_url": "https://api.github.com/repos/nosir/cleave.js/hooks",
  "issue_events_url": "https://api.github.com/repos/nosir/cleave.js/issues/events{/number}",
  "events_url": "https://api.github.com/repos/nosir/cleave.js/events",
  "assignees_url": "https://api.github.com/repos/nosir/cleave.js/assignees{/user}",
  "branches_url": "https://api.github.com/repos/nosir/cleave.js/branches{/branch}",
  "tags_url": "https://api.github.com/repos/nosir/cleave.js/tags",
  "blobs_url": "https://api.github.com/repos/nosir/cleave.js/git/blobs{/sha}",
  "git_tags_url": "https://api.github.com/repos/nosir/cleave.js/git/tags{/sha}",
  "git_refs_url": "https://api.github.com/repos/nosir/cleave.js/git/refs{/sha}",
  "trees_url": "https://api.github.com/repos/nosir/cleave.js/git/trees{/sha}",
  "statuses_url": "https://api.github.com/repos/nosir/cleave.js/statuses/{sha}",
  "languages_url": "https://api.github.com/repos/nosir/cleave.js/languages",
  "stargazers_url": "https://api.github.com/repos/nosir/cleave.js/stargazers",
  "contributors_url": "https://api.github.com/repos/nosir/cleave.js/contributors",
  "subscribers_url": "https://api.github.com/repos/nosir/cleave.js/subscribers",
  "subscription_url": "https://api.github.com/repos/nosir/cleave.js/subscription",
  "commits_url": "https://api.github.com/repos/nosir/cleave.js/commits{/sha}",
  "git_commits_url": "https://api.github.com/repos/nosir/cleave.js/git/commits{/sha}",
  "comments_url": "https://api.github.com/repos/nosir/cleave.js/comments{/number}",
  "issue_comment_url": "https://api.github.com/repos/nosir/cleave.js/issues/comments{/number}",
  "contents_url": "https://api.github.com/repos/nosir/cleave.js/contents/{+path}",
  "compare_url": "https://api.github.com/repos/nosir/cleave.js/compare/{base}...{head}",
  "merges_url": "https://api.github.com/repos/nosir/cleave.js/merges",
  "archive_url": "https://api.github.com/repos/nosir/cleave.js/{archive_format}{/ref}",
  "downloads_url": "https://api.github.com/repos/nosir/cleave.js/downloads",
  "issues_url": "https://api.github.com/repos/nosir/cleave.js/issues{/number}",
  "pulls_url": "https://api.github.com/repos/nosir/cleave.js/pulls{/number}",
  "milestones_url": "https://api.github.com/repos/nosir/cleave.js/milestones{/number}",
  "notifications_url": "https://api.github.com/repos/nosir/cleave.js/notifications{?since,all,participating}",
  "labels_url": "https://api.github.com/repos/nosir/cleave.js/labels{/name}",
  "releases_url": "https://api.github.com/repos/nosir/cleave.js/releases{/id}",
  "deployments_url": "https://api.github.com/repos/nosir/cleave.js/deployments",
  "created_at": "2016-05-18T12:45:03Z",
  "updated_at": "2021-10-07T10:05:31Z",
  "pushed_at": "2021-08-11T03:58:41Z",
  "git_url": "git://github.com/nosir/cleave.js.git",
  "ssh_url": "git@github.com:nosir/cleave.js.git",
  "clone_url": "https://github.com/nosir/cleave.js.git",
  "svn_url": "https://github.com/nosir/cleave.js",
  "homepage": "http://nosir.github.io/cleave.js",
  "size": 3579,
  "stargazers_count": 16975,
  "watchers_count": 16975,
  "language": "JavaScript",
  "has_issues": true,
  "has_projects": false,
  "has_downloads": true,
  "has_wiki": false,
  "has_pages": true,
  "forks_count": 1577,
  "mirror_url": null,
  "archived": false,
  "disabled": false,
  "open_issues_count": 178,
  "license": {
    "key": "apache-2.0",
    "name": "Apache License 2.0",
    "spdx_id": "Apache-2.0",
    "url": "https://api.github.com/licenses/apache-2.0",
    "node_id": "MDc6TGljZW5zZTI="
  },
  "allow_forking": true,
  "is_template": false,
  "topics": [
    "credit-card",
    "creditcard",
    "input",
    "input-mask",
    "telephone-number"
  ],
  "visibility": "public",
  "forks": 1577,
  "open_issues": 178,
  "watchers": 16975,
  "default_branch": "master",
  "temp_clone_token": null,
  "network_count": 1577,
  "subscribers_count": 200
}})
